# utils/mapping.py

INDOOR_CLASSES = {
    "bedroom": [
        "bedroom",
        "bedchamber"
    ],
     "living_room": [
        "living_room",
        "television_room"
    ],
    "bathroom": ["bathroom", "shower"],
    "kitchen": ["kitchen", "pantry"],
    "home_office": ["home_office"],
    "basement": ["basement", "utility_room"],
    "attic": ["attic"],
    "closet": ["closet"],
    "child_room": ["childs_room", "nursery", "playroom"],
    "hotel_room": ["hotel_room", "youth_hostel"],
    "dorm_room": ["dorm_room", "berth"],
    "classroom": ["classroom", "kindergarden_classroom"],
    "laboratory": ["biology_laboratory", "chemistry_lab", "physics_laboratory"],
    "lecture_room": ["lecture_room", "auditorium"],
    "library": ["library-indoor", "archive"],
    "hospital_room": ["hospital_room", "operating_room"],
    "clinic": ["veterinarians_office", "nursing_home"],
    "grocery_store": ["supermarket", "general_store-indoor"],
    "clothing_store": ["clothing_store", "shoe_shop"],
    "food_shop": ["bakery-shop", "candy_store", "ice_cream_parlor"],
    "pharmacy": ["pharmacy", "drugstore"],
    "mall": ["shopping_mall-indoor", "department_store"],
    "market": ["market-indoor", "bazaar-indoor", "flea_market-indoor"],
    "specialty_shop": [
        "gift_shop", "toyshop", "pet_shop",
        "jewelry_shop", "florist_shop-indoor"
    ],
    "bookstore": ["bookstore"],
    "butchers_shop": ["butchers_shop"],
    "hardware_store": ["hardware_store"],
    "fabric_store": ["fabric_store"],
    "auto_showroom": ["auto_showroom"],
    "restaurant": ["restaurant", "fastfood_restaurant", "pizzeria", "sushi_bar"],
    "restaurant_kitchen": ["restaurant_kitchen", "galley"],
    "bar": ["bar", "pub-indoor", "wet_bar", "beer_hall"],
    "cafeteria": ["cafeteria", "food_court"],
    "dining_space": ["dining_room", "dining_hall", "banquet_hall"],
    "theater": ["movie_theater-indoor", "stage-indoor"],
    "music_space": ["music_studio", "orchestra_pit"],
    "gym": ["gymnasium-indoor", "martial_arts_gym"],
    "sports_arena": [
        "arena-hockey", "arena-performance",
        "basketball_court-indoor", "boxing_ring",
        "ice_skating_rink-indoor"
    ],
    "game_area": ["amusement_arcade", "ball_pit"],
    "pool": ["swimming_pool-indoor", "jacuzzi-indoor", "sauna"],
    "television_studio": ["television_studio"],
    "museum": ["museum-indoor", "science_museum", "natural_history_museum"],
    "art_space": ["art_gallery", "art_studio", "artists_loft", "art_school"],
    "religious_space": ["church-indoor"],
    "government_space": ["legislative_chamber", "throne_room"],
     "airport": ["airport_terminal", "airplane_cabin"],
    "train": ["train_interior", "subway_station-platform"],
    "vehicle_interior": ["car_interior", "bus_interior"],
    "parking": ["parking_garage-indoor", "garage-indoor"],
     "factory": ["assembly_line", "auto_factory"],
    "server_room": ["server_room", "computer_room"],
    "storage": ["storage_room", "lock_chamber", "bank_vault"],
    "engine_room": ["engine_room"],
    "hangar": ["hangar-indoor"],
    "repair_shop": ["repair_shop"],
    "stable": ["stable"],
    "clean_room": ["clean_room"],
     "corridor": ["corridor"],
    "staircase": ["staircase"],
    "mezzanine": ["mezzanine"],
    "entrance_hall": ["entrance_hall"],
    "lobby": ["lobby", "reception", "waiting_room"],
    "elevator": ["elevator-door", "elevator_lobby", "elevator_shaft"],
    "escalator": ["escalator-indoor"],
    "atrium": ["atrium-public"],
    "jail": ["jail_cell"],
    "burial_site": ["catacomb", "burial_chamber"],
    "office": ["office", "office_cubicles"],
    "conference": ["conference_room", "conference_center"],
    "booth": ["booth-indoor"],
    "bow_window": ["bow_window-indoor"],
    "locker_room": ["locker_room"],
    "dressing_room": ["dressing_room"],
    "laundromat": ["laundromat"],
    "recreation_room": ["recreation_room"],
    "alcove": ["alcove"],
    "aquarium": ["aquarium"],
    "ballroom": ["ballroom"],
    "beauty_salon": ["beauty_salon"],
    "bowling_alley": ["bowling_alley"],
    "coffee_shop": ["coffee_shop"],
    "delicatessen": ["delicatessen"],
    "discotheque": ["discotheque"],
    "greenhouse": ["greenhouse-indoor"],
    "home_theater": ["home_theater"],
}

OUTDOOR_MERGE_RULES = {
    'air_transport': ['airfield', 'runway', 'heliport'],
    'rail_transport': ['railroad_track', 'train_station-platform'],
    'road_transport': ['highway', 'street', 'desert_road', 'field_road', 'driveway'],
    'bridge': ['bridge', 'viaduct', 'rope_bridge'],
    'parking': ['parking_lot', 'parking_garage-outdoor'],
    'station': ['bus_station-indoor'],
    'loading_area': ['loading_dock'],
    'stadium': ['stadium-baseball', 'stadium-football', 'stadium-soccer'],
    'sports_field': ['athletic_field-outdoor', 'baseball_field', 'football_field', 'soccer_field', 'volleyball_court-outdoor', 'golf_course', 'racecourse', 'raceway'],
    'ski_area': ['ski_resor', 'ski_slope'],
    'ice_rink': ['ice_skating_rink-outdoor'],
    'amusement_area': ['amusement_park', 'water_park', 'carrousel'],
    'play_area': ['playground', 'sandbox'],
    'swimming_area': ['swimming_pool-outdoor', 'swimming_hole', 'watering_hole'],
    'residential_building': ['house', 'cottage', 'mansion', 'chalet', 'manufactured_home', 'beach_house', 'tree_house'],
    'commercial_building': ['office_building', 'shopfront', 'general_store-outdoor', 'restaurant_patio', 'diner-outdoor', 'fastfood_restaurant'],
    'religious_building': ['church-outdoor', 'mosque-outdoor', 'synagogue-outdoor', 'temple-asia'],
    'historic_structure': ['castle', 'palace', 'ruin', 'kasbah', 'pagoda', 'arch', 'rock_arch'],
    'public_building': ['courthouse', 'embassy', 'hospital', 'schoolhouse', 'fire_station', 'library-outdoor', 'museum-outdoor'],
    'urban_area': ['downtown', 'residential_neighborhood', 'plaza', 'promenade', 'courtyard', 'campus'],
    'village': ['village', 'medina', 'slum'],
    'market': ['market-outdoor', 'bazaar-outdoor'],
    'yard': ['yard', 'lawn', 'patio', 'porch'],
    'forest': ['forest-broadleaf', 'rainforest', 'forest_path', 'forest_road', 'bamboo_forest'],
    'mountain': ['mountain', 'mountain_snowy', 'mountain_path'],
    'desert': ['desert-sand', 'desert-vegetation'],
    'water_body': ['river', 'lake-natural', 'pond', 'lagoon', 'ocean', 'creek', 'canal-natural', 'canal-urban'],
    'ice_landscape': ['glacier', 'iceberg', 'ice_floe', 'ice_shelf', 'snowfield'],
    'wetland': ['marsh', 'swamp'],
    'landform': ['canyon', 'cliff', 'valley', 'butte', 'badlands', 'volcano', 'tundra'],
    'farm_area': ['farm', 'barn', 'shed', 'corral', 'pasture', 'hayfield', 'stable'],
    'crop_field': ['corn_field', 'rice_paddy', 'wheat_field', 'field-cultivated', 'field-wild'],
    'orchard': ['orchard', 'vineyard', 'tree_farm'],
    'garden': ['formal_garden', 'botanical_garden', 'japanese_garden', 'zen_garden', 'topiary_garden', 'vegetable_garden', 'roof_garden'],
    'harbor': ['harbor', 'pier', 'landing_deck', 'boat_deck', 'boathouse'],
    'water_feature': ['waterfall', 'fountain', 'fishpond', 'hot_spring', 'wave'],
    'underwater': ['underwater-ocean_deep'],
    'industrial_area': ['industrial_area', 'construction_site', 'excavation'],
    'energy': ['oilrig', 'wind_farm', 'windmill', 'water_tower', 'dam'],
    'waste': ['junkyard', 'landfill'],
    'garage': ['garage-outdoor', 'hangar-outdoor'],
    'military': ['army_base'],
    'camping': ['campsite', 'hunting_lodge-outdoor', 'inn-outdoor', 'motel', 'hotel-outdoor'],
    'park': ['park', 'picnic_area', 'boardwalk'],
    'gazebo': ['gazebo-exterior', 'pavilion'],
    'cemetery': ['cemetery', 'mausoleum'],
    'doorway': ['doorway-outdoor'],
    'phone_booth': ['phone_booth', 'ticket_booth'],
    'tower': ['tower', 'lighthouse'],
    'crossing': ['crosswalk'],
    'sky': ['sky'],
    'arena': ['arena-rodeo'],
    'stage': ['stage-outdoor'],
    'grotto': ['grotto'],
    'igloo': ['igloo'],
    'aqueduct': ['aqueduct'],
    'arcade': ['arcade'],
    'alley': ['alley'],
    'balcony': ['balcony-exterior', 'balcony-interior'],
    'cockpit': ['cockpit'],
    'amphitheater': ['amphitheater'],
    'apartment_building-outdoor': ['apartment_building-outdoor'],
    'archaelogical_excavation': ['archaelogical_excavation'],
    'barndoor': ['barndoor'],
    'beach': ['beach'],
    'beer_garden': ['beer_garden'],
    'building_facade': ['building_facade'],
    'bullring': ['bullring'],
    'cabin-outdoor': ['cabin-outdoor'],
    'coast': ['coast'],
    'crevasse': ['crevasse'],
    'fire_escape': ['fire_escape'],
    'gas_station': ['gas_station'],
    'greenhouse-outdoor': ['greenhouse-outdoor'],
    'islet': ['islet'],
    'kennel-outdoor': ['kennel-outdoor'],
    'moat-water': ['moat-water'],
    'oast_house': ['oast_house'],
    'raft': ['raft'],
    'skyscraper': ['skyscraper'],
    'trench': ['trench'],
}